package eavesarp_ng

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"github.com/google/gopacket"
	"github.com/google/gopacket/layers"
	"github.com/google/gopacket/pcap"
	"net"
	"os"
)

type (
	SnacSniffHandler func(packet gopacket.Packet)
)

var (
	stopSnifferC = make(chan bool)
)

func getInterface(name string) (iface *net.Interface, ipnet *net.IPNet, err error) {

	iface, err = net.InterfaceByName(name)
	if err != nil {
		// TODO
		//println("error looking up network interface: ", err.Error())
		//os.Exit(1)
		return
	}

	var addrs []net.Addr
	addrs, err = iface.Addrs()
	if err != nil {
		// TODO
		//println("failed to obtain ip address from network interface: ", err.Error())
		//os.Exit(1)
		return
	} else {
		for _, a := range addrs {
			if n, ok := a.(*net.IPNet); ok && !n.IP.IsLoopback() {
				if ip4 := n.IP.To4(); ip4 != nil {
					ipnet = &net.IPNet{
						IP:   ip4,
						Mask: n.Mask[len(n.Mask)-4:],
					}
				}
			}
		}
	}

	return
}

func MainSniff(db *sql.DB, ifaceName string) {
	// SOURCE: https://github.com/google/gopacket/blob/master/examples/arpscan/arpscan.go

	defer db.Close()
	go ArpSender()
	defer func() {
		// TODO
		println("killing arp sender process")
		stopArpSenderC <- true
	}()

	go DnsSender()
	defer func() {
		// TODO
		println("killing dns sender process")
		stopDnsSenderC <- true
	}()

	//==========================
	// PREPARE NETWORK INTERFACE
	//==========================
	iface, addr, err := getInterface(ifaceName)
	if err != nil {
		// TODO
		println("failed to obtain interface and addr", err.Error())
		os.Exit(1)
	}

	//============================
	// PERPETUALLY CAPTURE PACKETS
	//============================

	println("starting packet capture")

	handle, err := pcap.OpenLive(iface.Name, 65536, true, pcap.BlockForever)
	if err != nil {
		// TODO
		println("error opening packet capture: ", err.Error())
		os.Exit(1)
	}
	defer handle.Close()
	if err = handle.SetBPFFilter("arp"); err != nil {
		// TODO
		println("failed to set bpf filter: ", err.Error())
		os.Exit(1)
	}

	src := gopacket.NewPacketSource(handle, layers.LayerTypeEthernet)
	in := src.Packets()

outer:
	for {
		var packet gopacket.Packet
		select {
		case <-stopSnifferC:
			break outer
		case packet = <-in:

			arp := GetArpLayer(packet)
			if arp == nil {
				continue
			}

			// Ignore ARP requests generated by our interface
			// TODO this should probably check all interfaces, not just the one
			//      we're sniffing
			if bytes.Equal(iface.HardwareAddr, arp.SourceHwAddress) {
				continue
			}

			u := newUnpackedArp(arp)

			switch arp.Operation {
			case layers.ARPRequest:

				//======================================
				// HANDLE PASSIVELY CAPTURED ARP REQUEST
				//======================================

				fmt.Printf("ARP Request: %s (%s) -> %s\n", u.SrcIp, u.SrcHw, u.DstIp)

				_, srcIp, dstIp, err := u.getOrCreateSnifferDbValues(db, PassiveArpMeth)
				// TODO log new IP discoveries

				if dstIp.MacId == nil && !activeArps.Has(dstIp.Value) && !dstIp.ArpResolved {

					//=================
					// SEND ARP REQUEST
					//=================

					arpSenderC <- ArpSenderArgs{
						operation: ArpReqOperation,
						handle:    handle,
						srcHw:     iface.HardwareAddr,
						srcIp:     addr.IP,
						dstIp:     arp.DstProtAddress,
						addActiveArp: func() (err error) {
							err = activeArps.Add(dstIp, func() error { return SetArpResolved(db, dstIp.Id) })
							if err != nil && !errors.Is(err, activeArpAlreadySet) {
								// TODO logging
								println("failed to watch for active arp response", err.Error())
								os.Exit(1)
							} else if err != nil {
								err = nil
							}
							return
						},
					}

					fmt.Printf("initiated active arp request for %v\n", dstIp.Value)
				}

				//====================
				// INCREMENT ARP COUNT
				//====================

				count, err := IncArpCount(db, srcIp.Id, dstIp.Id)
				if err != nil {
					// TODO
					println("failed to increment arp count: ", err.Error())
					os.Exit(1)
				}
				fmt.Printf("Incremented arp count: %s -> %s -> %d\n", srcIp.Value, dstIp.Value, count)

				//===================
				// DO NAME RESOLUTION
				//===================

				if !dnsFailCounter.Exceeded() {
					for _, ip := range []*Ip{srcIp, dstIp} {
						if !ip.PtrResolved {
							dnsSenderC <- DnsSenderArgs{
								kind:   PtrDnsKind,
								target: ip.Value,
								failure: func(e error) {
									if err := SetPtrResolved(db, *ip); err != nil {
										// TODO
										println("failed to set ptr to resolved: ", err.Error())
										os.Exit(1)
									}
								},
								after: func(names []string) {
									for _, name := range names {
										handlePtrName(db, ip, name, nil)
									}
								},
							}
						}
					}
				}

			case layers.ARPReply:

				//===================
				// HANDLE ARP REPLIES
				//===================

				if ip := activeArps.Get(u.SrcIp); ip != nil {
					fmt.Printf("ARP Response: %s (%s) -> %s (%s)\n", u.SrcIp, u.SrcHw, u.DstIp, u.DstHw)
					srcMac, srcIp, _, err := u.getOrCreateSnifferDbValues(db, ActiveArpMeth)
					if err != nil {
						// TODO
						println("failed to handle arp reply: ", err.Error())
						os.Exit(1)
					}
					fmt.Printf("received arp reply: %s (%s)\n", srcIp.Value, srcMac.Value)
				}
			}
		}
	}

	// TODO
	println("exiting main sniffer thread")
}

func (u unpackedArp) getOrCreateSnifferDbValues(db *sql.DB, arpMethod DiscMethod) (srcMac *Mac, srcIp *Ip,
  dstIp *Ip, err error) {

	//===============
	// HANDLE SRC MAC
	//===============

	srcMacBuff, err := GetOrCreateMac(db, u.SrcHw, arpMethod)
	if err != nil {
		// TODO
		println("failed to create mac: ", err.Error())
		os.Exit(1)
	}
	srcMac = &srcMacBuff

	//==============
	// HANDLE SRC IP
	//==============

	srcIpBuff, err := GetOrCreateIp(db, u.SrcIp, &srcMacBuff.Id, arpMethod, true, false)
	if err != nil {
		// TODO
		println("failed to create mac: ", err.Error())
		os.Exit(1)
	} else if srcIpBuff.MacId == nil {

		//============
		// SET SRC MAC
		//============
		// - the mac is unavailable when a _target_ IP address was discovered via ARP request
		// - since goc doesn't update records, this means we'll need to update it manually

		if _, err = db.Exec(`UPDATE ip SET mac_id=? WHERE id=?`, srcMac.Id, srcIpBuff.Id); err != nil {
			println("failed to update ip with mac address: ", err.Error())
			os.Exit(1)
		}
		srcIpBuff.MacId = &srcMac.Id
	}
	srcIp = &srcIpBuff

	if arpMethod == PassiveArpMeth {
		dstIpBuff, err := GetOrCreateIp(db, u.DstIp, nil, arpMethod, false, false)
		if err != nil {
			// TODO
			println("failed to create mac: ", err.Error())
			os.Exit(1)
		}
		dstIp = &dstIpBuff
	}

	return
}

func GetPacketTransportLayerInfo(packet gopacket.Packet) (proto string, dstPort int, err error) {
	transLayer := packet.TransportLayer()
	switch lT := transLayer.LayerType(); lT {
	case layers.LayerTypeTCP:
		layer := transLayer.(*layers.TCP)
		proto = "tcp"
		dstPort = int(layer.DstPort)
	case layers.LayerTypeUDP:
		layer := transLayer.(*layers.UDP)
		proto = "udp"
		dstPort = int(layer.DstPort)
	case layers.LayerTypeSCTP:
		layer := transLayer.(*layers.SCTP)
		proto = "sctp"
		dstPort = int(layer.DstPort)
	default:
		// TODO
		err = errors.New("unknown transport layer type captured")
	}
	return
}

func GetArpLayer(packet gopacket.Packet) *layers.ARP {
	if arpLayer := packet.Layer(layers.LayerTypeARP); arpLayer != nil {
		return arpLayer.(*layers.ARP)
	}
	return nil
}

// SnacSniffWriter should be run as a background process to receive
// packets that are written to a pcap file.
func SnacSniffWriter(ctx context.Context, c chan []byte, fileName string) (err error) {
	var handle *pcap.Handle
	if handle, err = pcap.OpenOffline(fileName); err != nil {
		return err
	}
	defer handle.Close()
outer:
	for {
		select {
		case <-ctx.Done():
			return nil
		case packetData := <-c:
			if err = handle.WritePacketData(packetData); err != nil {
				break outer
			}
		}
	}
	return
}

// SnacSniff is used to initiate a standalone packet capture for a
// specific source IP (srcIp) while passing each captured packet to
//a series of handlers.
func SnacSniff(ctx context.Context, ifaceName string, srcIp net.IP, handlers ...SnacSniffHandler) (err error) {

	iface, _, err := getInterface(ifaceName)
	if err != nil {
		println("failed to retrive interface and addr", err.Error())
		os.Exit(1)
	}

	println("starting snac packet capture")

	var handle *pcap.Handle
	handle, err = pcap.OpenLive(iface.Name, 655536, true, pcap.BlockForever)
	if err != nil {
		// TODO
		println("failed to start packet capture", err.Error())
		os.Exit(1)
	}
	defer handle.Close()

	if err = handle.SetBPFFilter(fmt.Sprintf("src host %s", srcIp.String())); err != nil {
		// TODO
		println("failed to set bpf filter", err.Error())
		os.Exit(1)
	}

	src := gopacket.NewPacketSource(handle, layers.LayerTypeEthernet)
	in := src.Packets()

	for {
		select {
		case <-ctx.Done():
			return
		case packet := <-in:

			if arp := GetArpLayer(packet); arp != nil && arp.Operation == layers.ARPRequest {
				// Respond with our MAC
				arpSenderC <- ArpSenderArgs{
					handle:       handle,
					operation:    layers.ARPReply,
					srcHw:        iface.HardwareAddr,
					srcIp:        srcIp,
					dstHw:        arp.DstHwAddress,
					dstIp:        arp.DstProtAddress,
					addActiveArp: nil,
				}
				continue
			}

			// Run handlers
			go func() {
				for _, h := range handlers {
					h(packet)
				}
			}()
		}
	}

	return
}
