on:
  push:
    tags:
      - '*-release'
jobs:
  build_eavesarp:
    name: Build Eavesarp
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
      - uses: actions/checkout@v3
      - name: build
        id: build-eavesarp
        run: |
          echo "installing dependencies"
          apt update && apt install clang build-essential libpcap-dev mingw-w64 wget zip -y
          cd cmd
          
          echo "building for linux"
          GOOS=linux GOARCH=amd64 go build -buildvcs=false -o eavesarp
          
          echo "building for windows"
          cd /tmp
          wget -O npcap.zip https://npcap.com/dist/npcap-sdk-1.13.zip
          unzip npcap.zip
          cd -
          CGO_ENABLED=1 GOOS=windows GARCH=amd64 \
            CGO_FLAGS="-I/tmp/Include" \
            CGO_LDFLAGS="-L/tmp/Lib/x64 -lwpcap -lPacket" \
            CC=x86_64-w64-mingw32-gcc \
            go build -buildvcs=false -o eavesarp.exe
      - name: release
        id: issue-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "eavesarp*"
          allowUpdates: "true"
          body: "Releasing ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}