on:
  push:
    tags:
      - '*-release'
jobs:
  build_eavesarp:
    name: Build Eavesarp
    runs-on: ubuntu-latest
    container:
      image: golang:1.23.1-bookworm
    steps:
      - uses: actions/checkout@v3
      - name: build
        id: build-eavesarp
        run: |
          apt update && apt install build-essential libpcap-dev -y
          cd cmd
          GOOS=linux GOARCH=amd64 go build -buildvcs=false -o eavesarp.elf
          GOOS=windows GOARCH=amd64 go build -buildvcs=false -o eavesarp.exe
          GOOS=darwin GOARCH=amd64 go build -buildvcs=false -o eavesarp.darwin_amd64
          GOOS=darwin GOARCH=amd64 go build -buildvcs=false -o eavesarp.darwin_arm64
      - name: release
        id: issue-release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "eavesarp.*"
          allowUpdates: "true"
          body: "Releasing ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}